name: Get customised email message with PR info
description: Get email body from branch name and send it
inputs:
  repo-name:
    description: 'Repository name'
    required: true
  branch-name:
    description: 'Branch name'
    required: true
  pr-title:
    description: 'Pull request title'
  pr-url:
    description: 'Pull request url'
outputs:
  subject:
    description: Email subject
  body:
    description: Email body
runs:
  using: 'node12'
  main: 'index.js'