name: Send Email on PR open
description: Get email body from branch name and send it
inputs:
  branch-name:
    description: 'Branch name'
    required: true
  pr-title:
    description: 'Pull request title'
  pr-url:
    description: 'Pull request url'
  sendgrid-api-key:
    description: 'API key needed for sending emails'
  sender-email:
    description: 'Sender email'
outputs:
  subject:
    description: Email subject
  body:
    description: Email body
runs:
  using: 'node12'
  main: 'index.js'